"use strict";
const assert = require('node:assert/strict');
global.RewardLab = require('./core.js');
global.LabContent = require('./content.js');
const V = require('./video.js');
const run = RewardLab.create({preset:'bell', seed:42});
for(let i=0;i<7;i++) RewardLab.step(run);
const before=JSON.stringify(run);
let labels=[], bars=[];
const context={fillText:s=>labels.push(s),fillRect:(...v)=>bars.push(v),beginPath(){},moveTo(){},lineTo(){},stroke(){},strokeRect(){}};
const canvas={getContext:()=>context};
let state={run,methods:['ppo'],focus:'ppo',shown:7,horizon:100,pace:300,phase:'update',sounding:true,bin:5};
V.draw(canvas,state,{});
assert(labels.includes('Update 7 / 100'));
assert(labels.some(s=>s.startsWith('PPO sound')));
assert(labels.includes('4× playback · update'));
const ppoBars=bars.slice();
labels=[];bars=[];
state={...state,methods:['grpo'],focus:'grpo',shown:3,pace:1200,sounding:false};
V.draw(canvas,state,{});
assert(labels.includes('Update 3 / 100'));
assert(labels.includes('Sound off'));
assert(!labels.some(s=>s.startsWith('PPO sound')));
assert.notDeepEqual(bars,ppoBars);
assert.equal(JSON.stringify(run),before);
assert.equal(V.format({isTypeSupported:()=>false}),undefined);
assert.equal(V.format({isTypeSupported:x=>x.startsWith('video/webm')})[1],'webm');
console.log('PASS: live update position, selected policy, speed, sound state and chart data; recording does not mutate simulation.');
